server:
   port: 8083

spring:
   datasource:
      username: sa
      url: jdbc:h2:mem:testdb

keycloak:
   server:
      contextPath: /auth
      adminUser:
         username: taketoday-admin
         password: pass
      realmImportFile: feign-realm.json

