<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cn.tuyucheng.taketoday</groupId>
    <artifactId>parent-modules</artifactId>
    <version>1.0.0</version>
    <relativePath>../..</relativePath>
  </parent>
  <groupId>cn.tuyucheng.taketoday.maven.polyglot</groupId>
  <artifactId>maven-polyglot-yml-app</artifactId>
  <version>1.0.0</version>
  <name>YAML Demo</name>
  <properties>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
  </properties>
</project>