package cn.tuyucheng.taketoday.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "EmployeeService", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/")
@XmlSeeAlso({
      ObjectFactory.class
})
public interface EmployeeService {


   /**
    * @param arg0
    * @return returns com.tuyucheng.jaxws.client.Employee
    * @throws EmployeeNotFound_Exception
    */
   @WebMethod
   @WebResult(targetNamespace = "")
   @RequestWrapper(localName = "getEmployee", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.GetEmployee")
   @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.GetEmployeeResponse")
   @Action(input = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/getEmployeeRequest", output = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/getEmployeeResponse", fault = {
         @FaultAction(className = EmployeeNotFound_Exception.class, value = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/getEmployee/Fault/EmployeeNotFound")
   })
   public Employee getEmployee(
         @WebParam(name = "arg0", targetNamespace = "")
         int arg0)
         throws EmployeeNotFound_Exception
   ;

   /**
    * @param arg1
    * @param arg0
    * @return returns com.tuyucheng.jaxws.client.Employee
    * @throws EmployeeNotFound_Exception
    */
   @WebMethod
   @WebResult(targetNamespace = "")
   @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.UpdateEmployee")
   @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.UpdateEmployeeResponse")
   @Action(input = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/updateEmployeeRequest", output = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/updateEmployeeResponse", fault = {
         @FaultAction(className = EmployeeNotFound_Exception.class, value = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/updateEmployee/Fault/EmployeeNotFound")
   })
   public Employee updateEmployee(
         @WebParam(name = "arg0", targetNamespace = "")
         int arg0,
         @WebParam(name = "arg1", targetNamespace = "")
         String arg1)
         throws EmployeeNotFound_Exception
   ;

   /**
    * @return returns java.util.List<com.tuyucheng.jaxws.client.Employee>
    */
   @WebMethod
   @WebResult(targetNamespace = "")
   @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.GetAllEmployees")
   @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.GetAllEmployeesResponse")
   @Action(input = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/getAllEmployeesRequest", output = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/getAllEmployeesResponse")
   public List<Employee> getAllEmployees();

   /**
    * @param arg0
    * @return returns boolean
    * @throws EmployeeNotFound_Exception
    */
   @WebMethod
   @WebResult(targetNamespace = "")
   @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.DeleteEmployee")
   @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.DeleteEmployeeResponse")
   @Action(input = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/deleteEmployeeRequest", output = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/deleteEmployeeResponse", fault = {
         @FaultAction(className = EmployeeNotFound_Exception.class, value = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/deleteEmployee/Fault/EmployeeNotFound")
   })
   public boolean deleteEmployee(
         @WebParam(name = "arg0", targetNamespace = "")
         int arg0)
         throws EmployeeNotFound_Exception
   ;

   /**
    * @param arg1
    * @param arg0
    * @return returns com.tuyucheng.jaxws.client.Employee
    * @throws EmployeeAlreadyExists_Exception
    */
   @WebMethod
   @WebResult(targetNamespace = "")
   @RequestWrapper(localName = "addEmployee", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.AddEmployee")
   @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.AddEmployeeResponse")
   @Action(input = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/addEmployeeRequest", output = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/addEmployeeResponse", fault = {
         @FaultAction(className = EmployeeAlreadyExists_Exception.class, value = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/addEmployee/Fault/EmployeeAlreadyExists")
   })
   public Employee addEmployee(
         @WebParam(name = "arg0", targetNamespace = "")
         int arg0,
         @WebParam(name = "arg1", targetNamespace = "")
         String arg1)
         throws EmployeeAlreadyExists_Exception
   ;

   /**
    * @return returns int
    */
   @WebMethod
   @WebResult(targetNamespace = "")
   @RequestWrapper(localName = "countEmployees", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.CountEmployees")
   @ResponseWrapper(localName = "countEmployeesResponse", targetNamespace = "http://bottomup.server.jaxws.tuyucheng.com/", className = "com.tuyucheng.jaxws.client.CountEmployeesResponse")
   @Action(input = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/countEmployeesRequest", output = "http://bottomup.server.jaxws.tuyucheng.com/EmployeeService/countEmployeesResponse")
   public int countEmployees();

}
