### invalid email and valid password
POST {{baseURL}}/loginform
Accept-Language: zh-CN
Content-Type: application/json

{
  "email": "",
  "password": "123456"
}

### valid email and invalid password
POST {{baseURL}}/loginform
Accept-Language: zh-CN
Content-Type: application/json

{
  "email": "halo@qq.com"
}

### valid email and valid password
POST {{baseURL}}/loginform
Accept-Language: zh-CN
Content-Type: application/json

{
  "email": "halo@qq.com",
  "password": "123456"
}

### invalid email and invalid password
POST {{baseURL}}/loginform
Accept-Language: zh-CN
Content-Type: application/json

{
  "email": ""
}