apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
    name: tuyucheng-event
spec:
    broker: tuyucheng
    filter:
        attributes:
            type: GreetUser
    subscriber:
        ref:
            apiVersion: serving.knative.dev/v1
            kind: Service
            name: quarkus-funqy-project