/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_tuyucheng_taketoday_jni_HelloWorldJNI */

#ifndef _Included_cn_tuyucheng_taketoday_jni_HelloWorldJNI
#define _Included_cn_tuyucheng_taketoday_jni_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_tuyucheng_taketoday_jni_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_cn_tuyucheng_taketoday_jni_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
