/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_tuyucheng_taketoday_jni_RegisterNativesHelloWorldJNI */

#ifndef _Included_cn_tuyucheng_taketoday_jni_RegisterNativesHelloWorldJNI
#define _Included_cn_tuyucheng_taketoday_jni_RegisterNativesHelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_tuyucheng_taketoday_jni_RegisterNativesHelloWorldJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_tuyucheng_taketoday_jni_RegisterNativesHelloWorldJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     cn_tuyucheng_taketoday_jni_RegisterNativesHelloWorldJNI
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_tuyucheng_taketoday_jni_RegisterNativesHelloWorldJNI_register
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
