server:
   port: 8085

spring:
   pulsar:
      client:
         service-url: pulsar://localhost:6650
      defaults:
         type-mappings:
            -  message-type: cn.tuyucheng.taketoday.springpulsar.User
               schema-info:
                  schema-type: JSON