drop table if exists USERS;
drop table if exists country;
drop table if exists BOOK;

create table USERS
(
   ID     INTEGER GENERATED BY DEFAULT AS IDENTITY,
   NAME   varchar(100) not null,
   STATUS int,
   PRIMARY KEY (ID)
);

CREATE TABLE country
(
   id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(128) NOT NULL,
   PRIMARY KEY (id)
);

create table BOOK
(
   ID   INTEGER GENERATED BY DEFAULT AS IDENTITY,
   NAME varchar(128) not null,
   PRIMARY KEY (ID)
);